@baseUrl = http://localhost:2609

GET {{baseUrl}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTg5MDQxMDAsImV4cCI6MTU5ODkwNzcwMCwiYXVkIjpbNzddfQ.uH_cHQc23mbs34Rf32vwIxQz2MY0crJysetya2aLY1o

### Login route
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "email": "vtmn1212@gmail.com",
    "password": "123456"
}

### Register route
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
    "email": "vtmn1212@gmail.com",
    "password": "123456",
    "firstname": "Nhung",
    "lastname": "Vo",
    "dob": "12/12/1999"
}

### Refresh token route
POST {{baseUrl}}/api/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTg5MDQxMDAsImV4cCI6MTYzMDQ2MTcwMCwiYXVkIjpbNzddfQ.K2BIvOxeQiUlwXpmNmckv73un1lGWaNDU3TsJK5MlcQ"
}

### Logout route
DELETE {{baseUrl}}/api/auth/logout